### ISSUE TITLE
Very slow loading of PN series in Mathematica 12.1.0.0

### ISSUE THREAD

**Issue by nielsw2** [BlackHolePerturbationToolkit/PostNewtonianSelfForce#3]
In Mathematica 12.1.0.0 the PN series take ages to load. `Timing[PostNewtonianExpansion["/Schwarzschild/Circular/Flux/Horizon"]]` returns 18 seconds.

The same command on Mathematica 12.0.0.0 takes 0.44 seconds. 
In Mathematica 11.2.0.0 it takes 0.03 seconds.
In Mathematica 10.4.1 it takes 0.09 seconds.

**Comment by barrywardell** [comment]
This appears to be a generic problem with 12.1 when assigning a SeriesData object to a variable. For example, just doing Get["SeriesData/Schwarzschild/Circular/Flux/Horizon.m"] takes a very long time also, and this can be narrowed down to the presence of a SeriesData object in the file. We should report this to Wolfram. In the meantime, converting to mx appears to restore the original performance.

**Comment by barrywardell** [comment]
This is still an issue with 13.0.1

**Comment by barrywardell** [comment]
And with 13.1

**Comment by barrywardell** [comment]
It might be that the best solution is to move away from using SeriesData unless explicitly asked for.
